ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER USER_JAVA IDENTIFIED BY "java01"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER USER_JAVA QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO USER_JAVA;

GRANT "RESOURCE" TO USER_JAVA;

ALTER USER USER_JAVA DEFAULT ROLE "RESOURCE";
